### ISSUE TITLE
Сделать обработку ситуации когда не смогли найте TestSuite

### ISSUE THREAD

**Issue by ehles** [ehles/trep#4]
Сейчас, если не нашли TestSuite выводится совершенно непонятная ошибка

> Configuration found under:configs/trep.yaml
> Traceback (most recent call last):
>   File "/home/jenkins/trep/bin/trep", line 5, in <module>
>     pkg_resources.run_script('trep==0.1', 'trep')
>   File "/home/jenkins/trep/local/lib/python2.7/site-packages/pkg_resources.py", line 488, in run_script
>     self.require(requires)[0].run_script(script_name, ns)
>   File "/home/jenkins/trep/local/lib/python2.7/site-packages/pkg_resources.py", line 1354, in run_script
>     execfile(script_filename, namespace, namespace)
>   File "/home/jenkins/trep/lib/python2.7/site-packages/trep-0.1-py2.7.egg/EGG-INFO/scripts/trep", line 75, in <module>
>     main()
>   File "/home/jenkins/trep/lib/python2.7/site-packages/trep-0.1-py2.7.egg/EGG-INFO/scripts/trep", line 71, in main
>     reporter.execute()
>   File "/home/jenkins/trep/local/lib/python2.7/site-packages/trep-0.1-py2.7.egg/trep/reporter.py", line 169, in execute
>     cases = self.find_testrail_cases(xunit_suite)
>   File "/home/jenkins/trep/local/lib/python2.7/site-packages/trep-0.1-py2.7.egg/trep/reporter.py", line 137, in find_testrail_cases
>     cases = self.suite.cases()
> AttributeError: 'NoneType' object has no attribute 'cases'

**Comment by ehles** [comment]
done
